# Generated by Django 4.0 on 2021-12-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.PositiveIntegerField(unique=True)),
                ('make', models.CharField(max_length=100)),
                ('modelo', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
