# Generated by Django 4.0 on 2021-12-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vin',
            field=models.CharField(max_length=100),
        ),
    ]
